In [243]:
import pandas as pd

In [244]:
df=pd.read_csv(r'C:\Users\fathi\OneDrive\Desktop\5thsem_OJT\project_diabetes\data\raw\project1_diabetes_raw.csv')

confrm the load succeeded

In [245]:
len(df)

968

load only the first few rows

In [246]:
df_100=pd.read_csv(r'C:\Users\fathi\OneDrive\Desktop\5thsem_OJT\project_diabetes\data\raw\project1_diabetes_raw.csv')

In [247]:
len(df_100)

968

record the dataset dimensions

In [248]:
df.shape

(968, 14)

In [249]:
df.shape[0]

968

In [250]:
df.shape[1]

14

list every column name

In [251]:
df.columns.to_list()

['patient_id',
 'age',
 'gender',
 'pregnancies',
 'glucose',
 'blood_pressure',
 'skin_thickness',
 'insulin',
 'bmi',
 'diabetes_pedigree',
 'physical_activity',
 'smoker',
 'last_checkup_date',
 'outcome']

inpest the inferrend types

In [252]:
df.dtypes

patient_id               str
age                  float64
gender                   str
pregnancies            int64
glucose                int64
blood_pressure         int64
skin_thickness         int64
insulin                int64
bmi                  float64
diabetes_pedigree    float64
physical_activity        str
smoker                   str
last_checkup_date        str
outcome                int64
dtype: object

In [253]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79.0,male,0,124,71,30,0,23.4,0.588,NaN,No,20/04/2023,0
1,P00108,37.0,Male,0,153,85,24,42,33.9,0.192,medium,Y,03/05/2024,1
2,P00517,39.0,F,0,142,68,22,159,26.9,0.777,low,NaN,08/07/2023,0
3,P00687,68.0,female,7,121,88,0,0,29.0,1.217,NaN,Y,14/04/2024,1
4,P00927,75.0,female,0,107,84,31,101,21.2,0.278,Low,No,27/01/2024,0
5,P00755,37.0,female,0,145,80,0,0,22.0,0.488,HIGH,Yes,10/01/2024,0
6,P00431,58.0,Male,5,95,72,0,170,27.2,0.197,HIGH,N,25/12/2023,0
7,P00542,58.0,Female,3,150,68,17,0,46.0,0.808,Medium,No,20/06/2024,1
8,P00929,32.0,Female,6,129,74,0,226,20.6,0.655,High,NaN,15/10/2023,1
9,P00513,61.0,Female,0,161,77,35,201,35.0,1.229,Medium,Y,22/12/2023,1

look at the bottom of the file

In [254]:
df.tail(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
958,P00584,47.0,Female,0,107,59,26,98,32.7,0.050,HIGH,No,20/07/2023,0
959,P00674,42.0,Female,5,124,71,22,121,NaN,0.400,NaN,N,01/06/2024,0
960,P00333,59.0,Male,0,141,67,44,305,28.8,0.705,Low,NaN,27/03/2023,1
961,P00270,36.0,Male,0,99,52,13,10,20.8,0.432,medium,Y,12/05/2024,0
962,P00501,39.0,Male,0,92,62,45,16,34.5,0.143,Medium,Yes,01/10/2023,0
963,P00338,64.0,male,2,0,81,34,0,40.3,0.641,Medium,Yes,17/11/2023,0
964,P00092,71.0,F,0,140,64,37,0,33.4,0.116,Low,Y,20/05/2023,1
965,P00081,40.0,Female,0,130,73,0,258,20.1,0.709,Low,N,07/06/2023,0
966,P00704,52.0,F,4,123,76,22,189,38.9,0.540,High,N,05/06/2024,0
967,P00922,42.0,Male,0,114,73,34,0,28.2,0.819,medium,N,10/10/2023,0

take a reproducible random sample

In [255]:
df.sample(10,random_state=7)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
684,P00739,23.0,female,0,131,66,0,68,23.4,0.653,low,No,03/07/2024,0
564,P00518,74.0,Female,0,104,76,21,0,39.8,0.926,low,Yes,14/07/2024,0
384,P00688,26.0,Male,0,124,74,22,197,30.7,0.612,medium,N,08/06/2023,0
24,P00836,66.0,M,5,115,70,21,42,18.9,0.403,Medium,N,28/07/2023,0
299,P00121,51.0,Female,6,122,77,32,188,35.9,0.184,NaN,N,15/01/2023,0
171,P00203,53.0,Male,0,82,80,42,146,34.1,0.881,Medium,Yes,15/12/2023,0
839,P00844,79.0,F,2,107,62,16,62,34.8,0.050,HIGH,NaN,23/07/2023,0
568,P00009,76.0,Female,0,132,65,0,0,NaN,0.541,High,N,11/01/2024,0
351,P00823,39.0,Female,7,94,90,0,0,NaN,0.541,low,N,14/07/2023,0
168,P00180,38.0,Female,0,75,56,0,86,29.8,0.473,low,N,22/07/2024,0

run the schema view

In [256]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 968 entries, 0 to 967
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         968 non-null    str
 1   age                959 non-null    float64
 2   gender             968 non-null    str
 3   pregnancies        968 non-null    int64
 4   glucose            968 non-null    int64
 5   blood_pressure     968 non-null    int64
 6   skin_thickness     968 non-null    int64
 7   insulin            968 non-null    int64
 8   bmi                930 non-null    float64
 9   diabetes_pedigree  968 non-null    float64
 10  physical_activity  910 non-null    str
 11  smoker             921 non-null    str
 12  last_checkup_date  968 non-null    str
 13  outcome            968 non-null    int64
dtypes: float64(3), int64(6), str(5)
memory usage: 106.0 KB

In [257]:
df.describe(include="all")

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
count,968,959.000000,968,968.000000,968.000000,968.000000,968.000000,968.000000,930.000000,968.000000,910,921,968,968.000000
unique,950,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,4,499,NaN
top,P00826,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medium,N,11/01/2024,NaN
freq,2,NaN,223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159,380,8,NaN
mean,NaN,49.883212,NaN,1.841942,114.324380,68.558884,20.596074,97.250000,30.796452,0.461834,NaN,NaN,NaN,0.286157
std,NaN,17.581570,NaN,2.616236,34.571781,19.449206,14.174823,118.072391,9.346399,0.285026,NaN,NaN,NaN,0.452197
min,NaN,21.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,NaN,NaN,NaN,0.000000
25%,NaN,35.000000,NaN,0.000000,95.000000,63.000000,8.000000,0.000000,26.200000,0.243500,NaN,NaN,NaN,0.000000
50%,NaN,50.000000,NaN,0.000000,116.000000,71.000000,22.000000,83.000000,30.900000,0.445500,NaN,NaN,NaN,0.000000
75%,NaN,65.000000,NaN,4.000000,136.000000,79.000000,31.000000,161.000000,35.675000,0.654250,NaN,NaN,NaN,1.000000
max,NaN,81.000000,NaN,8.000000,215.000000,107.000000,67.000000,1399.000000,94.500000,1.532000,NaN,NaN,NaN,1.000000

count distinct values in every text column

In [258]:
df['gender'].nunique

<bound method IndexOpsMixin.nunique of 0        male
1        Male
2           F
3      female
4      female
        ...
963      male
964         F
965    Female
966         F
967      Male
Name: gender, Length: 968, dtype: str>

count ocurebeces including missing values

In [259]:
df['gender'].value_counts(dropna=False)

gender
Female     223
Male       207
female     207
F          120
male       118
M           53
Male        12
Female       7
male         7
F            7
female       4
M            3
Name: count, dtype: int64

# value counts of outcome

In [260]:
df.value_counts('outcome')

outcome
0    691
1    277
Name: count, dtype: int64

In [261]:
df["outcome"].value_counts(normalize=True)

outcome
0    0.713843
1    0.286157
Name: proportion, dtype: float64

compare group size

In [262]:
df.groupby("outcome").size()

outcome
0    691
1    277
dtype: int64

compare average measurements across the groups

In [263]:
df.groupby("outcome").mean(numeric_only=True)

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree
outcome,,,,,,,,
0,47.922287,1.816208,108.596237,68.555716,20.824891,97.204052,30.303916,0.441114
1,54.711191,1.906137,128.613718,68.566787,20.025271,97.364621,32.025940,0.513520

In [264]:
df.groupby("outcome")[["age","glucose"]].mean()

               age     glucose
outcome
0        47.922287  108.596237
1        54.711191  128.613718

rank feature by diffrerence

# Data cleaning 
d2

count missing values per column

In [265]:
df.isnull().sum()

patient_id            0
age                   9
gender                0
pregnancies           0
glucose               0
blood_pressure        0
skin_thickness        0
insulin               0
bmi                  38
diabetes_pedigree     0
physical_activity    58
smoker               47
last_checkup_date     0
outcome               0
dtype: int64

In [266]:
df.isnull().sum().sum()

np.int64(152)

express missingmess as a proportion

In [267]:
df.isnull().mean()

patient_id           0.000000
age                  0.009298
gender               0.000000
pregnancies          0.000000
glucose              0.000000
blood_pressure       0.000000
skin_thickness       0.000000
insulin              0.000000
bmi                  0.039256
diabetes_pedigree    0.000000
physical_activity    0.059917
smoker               0.048554
last_checkup_date    0.000000
outcome              0.000000
dtype: float64

inspect the affected rows

In [268]:
df[df['physical_activity'].isnull()]
df[df.isnull().any(axis=1)]

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79.0,male,0,124,71,30,0,23.4,0.588,NaN,No,20/04/2023,0
2,P00517,39.0,F,0,142,68,22,159,26.9,0.777,low,NaN,08/07/2023,0
3,P00687,68.0,female,7,121,88,0,0,29.0,1.217,NaN,Y,14/04/2024,1
8,P00929,32.0,Female,6,129,74,0,226,20.6,0.655,High,NaN,15/10/2023,1
10,P00300,61.0,female,0,90,70,14,10,NaN,0.050,low,N,19/02/2023,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,P00505,24.0,Male,0,83,67,22,98,NaN,0.726,medium,N,28/02/2024,0
938,P00082,35.0,Female,0,71,93,29,257,17.8,0.985,NaN,N,11/12/2024,0
955,P00622,48.0,female,7,140,82,34,162,27.5,0.885,NaN,Yes,27/07/2023,0
959,P00674,42.0,Female,5,124,71,22,121,NaN,0.400,NaN,N,01/06/2024,0
960,P00333,59.0,Male,0,141,67,44,305,28.8,0.705,Low,NaN,27/03/2023,1

count the placeholders

In [269]:
(df['glucose']==0).sum()

np.int64(29)

In [270]:
placeholder_cols=["glucose","blood_pressure","skin_thickness","insulin","bmi"]
for c in placeholder_cols:
    print(c,(df[c]==0).sum(),"zero")

glucose 29 zero
blood_pressure 48 zero
skin_thickness 213 zero
insulin 269 zero
bmi 18 zero

convert placeholders to missing values

In [271]:
import numpy as np

In [272]:
df["glucose"]=df["glucose"].replace(0,np.nan)

In [273]:
before_missing =df.isnull().sum().sum()
for c in placeholder_cols:
    df[c]= df[c].replace(0,np.nan)

In [274]:
df.isnull().sum()

patient_id             0
age                    9
gender                 0
pregnancies            0
glucose               29
blood_pressure        48
skin_thickness       213
insulin              269
bmi                   56
diabetes_pedigree      0
physical_activity     58
smoker                47
last_checkup_date      0
outcome                0
dtype: int64

In [275]:
df.isnull().mean()

patient_id           0.000000
age                  0.009298
gender               0.000000
pregnancies          0.000000
glucose              0.029959
blood_pressure       0.049587
skin_thickness       0.220041
insulin              0.277893
bmi                  0.057851
diabetes_pedigree    0.000000
physical_activity    0.059917
smoker               0.048554
last_checkup_date    0.000000
outcome              0.000000
dtype: float64

fill  numeric  columns

In [276]:
df["glucose"] =df["glucose"].fillna(df["glucose"].mean())

In [277]:
col_fill =['age','blood_pressure','skin_thickness','insulin','bmi']
for i in col_fill:
    df[i]=df[i].fillna(df[i].median())

In [278]:
df.isnull().sum()

patient_id            0
age                   0
gender                0
pregnancies           0
glucose               0
blood_pressure        0
skin_thickness        0
insulin               0
bmi                   0
diabetes_pedigree     0
physical_activity    58
smoker               47
last_checkup_date     0
outcome               0
dtype: int64

fill categorical columns

In [279]:
fill_columns=["smoker","physical_activity"]
for c in fill_columns:
    df[c]=df[c].fillna("unknown")

verify no missing values remain

In [280]:

df.isnull().sum().sum()

np.int64(0)

remove stray whitespace

In [281]:
df.gender.unique()

<StringArray>
[   'male',    'Male',       'F',  'female',  'Female',       'M', 'female ',
      'M ',   'Male ', 'Female ',   'male ',      'F ']
Length: 12, dtype: str

In [282]:
df["gender"]= df["gender"].str.strip()

In [283]:
df.value_counts("gender")

gender
Female    230
Male      219
female    211
F         127
male      125
M          56
Name: count, dtype: int64

In [284]:

for c in fill_columns:
    df[c]=df[c].str.strip()

standardise captitalisation

In [285]:
df["gender"] =df["gender"].str.lower()

In [286]:
df["physical_activity"] =df["physical_activity"].str.title()

In [287]:
df.value_counts("gender")

gender
female    441
male      344
f         127
m          56
Name: count, dtype: int64

In [288]:
df["smoker"] =df["smoker"].str.upper()

unify equivalent categories

In [289]:
df['gender']=df['gender'].replace({'f':'female','m':'male'})

In [290]:
df.value_counts("gender")

gender
female    568
male      400
Name: count, dtype: int64

In [291]:
df['smoker']=df['smoker'].replace({'Y':'YES','N':'NO'})

In [292]:
df.value_counts("smoker")

smoker
NO         629
YES        292
UNKNOWN     47
Name: count, dtype: int64

convert text dates to real dates

In [293]:
df['last_checkup_date'] =pd.to_datetime(df['last_checkup_date'])
df['last_checkup_date'] =pd.to_datetime(df['last_checkup_date'],dayfirst=True)

C:\Users\fathi\AppData\Local\Temp\ipykernel_39732\1214819992.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['last_checkup_date'] =pd.to_datetime(df['last_checkup_date'])

correct remaning type mismathes

In [294]:
df['age']=df['age'].round().astype(int)
df.value_counts('age')

age
21    27
55    27
50    25
29    22
37    21
      ..
47    11
65    10
42    10
64     9
78     9
Name: count, Length: 61, dtype: int64

count exact duplicate

In [295]:
df.duplicated().sum()

np.int64(18)

inspect them before removing

In [296]:
df[df.duplicated(keep=False)]

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79,male,0,124.000000,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0
12,P00061,68,male,0,82.000000,63.0,20.0,10.0,33.7,0.191,Medium,NO,2024-08-18,0
21,P00446,60,female,0,90.000000,42.0,29.0,187.0,28.2,0.630,High,YES,2024-03-10,0
57,P00669,48,female,2,111.000000,59.0,26.0,147.0,30.5,0.380,High,YES,2024-01-11,0
80,P00881,46,female,4,131.000000,87.0,9.0,136.0,19.7,1.009,Low,NO,2023-04-09,1
92,P00483,73,female,0,127.000000,59.0,25.0,208.0,37.8,0.196,Low,NO,2024-05-06,0
122,P00455,73,male,0,115.000000,53.0,24.0,124.0,31.7,0.131,Low,YES,2023-08-26,0
156,P00061,68,male,0,82.000000,63.0,20.0,10.0,33.7,0.191,Medium,NO,2024-08-18,0
158,P00501,39,male,0,92.000000,62.0,45.0,16.0,34.5,0.143,Medium,YES,2023-10-01,0
178,P00372,62,male,2,54.000000,73.0,26.0,102.0,35.9,0.311,Medium,YES,2024-09-18,0
187,P00485,23,male,8,75.000000,70.0,32.0,124.0,33.1,0.858,Medium,NO,2024-07-01,0
207,P00926,43,female,0,179.000000,61.0,10.0,124.0,31.1,0.871,Low,NO,2024-05-09,0
220,P00720,40,female,0,93.000000,72.0,26.0,228.0,36.5,0.671,High,NO,2023-12-07,0
230,P00372,62,male,2,54.000000,73.0,26.0,102.0,35.9,0.311,Medium,YES,2024-09-18,0
261,P00409,66,female,0,117.855165,73.0,26.0,232.0,31.9,0.624,Low,YES,2024-12-11,1
361,P00881,46,female,4,131.000000,87.0,9.0,136.0,19.7,1.009,Low,NO,2023-04-09,1
382,P00160,29,male,1,157.000000,64.0,28.0,246.0,19.8,0.513,Medium,NO,2023-10-20,1
390,P00014,25,female,0,120.000000,65.0,22.0,10.0,29.7,0.552,Medium,NO,2023-04-25,0
401,P00720,40,female,0,93.000000,72.0,26.0,228.0,36.5,0.671,High,NO,2023-12-07,0
420,P00483,73,female,0,127.000000,59.0,25.0,208.0,37.8,0.196,Low,NO,2024-05-06,0
449,P00611,54,female,0,163.000000,68.0,37.0,10.0,36.9,0.442,High,NO,2024-05-24,1
464,P00926,43,female,0,179.000000,61.0,10.0,124.0,31.1,0.871,Low,NO,2024-05-09,0
479,P00348,22,male,5,144.000000,82.0,33.0,124.0,27.1,0.125,High,NO,2023-04-03,0
483,P00777,67,male,0,136.000000,79.0,63.0,181.0,36.4,0.050,Low,YES,2024-02-25,0
490,P00485,23,male,8,75.000000,70.0,32.0,124.0,33.1,0.858,Medium,NO,2024-07-01,0
509,P00669,48,female,2,111.000000,59.0,26.0,147.0,30.5,0.380,High,YES,2024-01-11,0
524,P00611,54,female,0,163.000000,68.0,37.0,10.0,36.9,0.442,High,NO,2024-05-24,1
547,P00446,60,female,0,90.000000,42.0,29.0,187.0,28.2,0.630,High,YES,2024-03-10,0
642,P00160,29,male,1,157.000000,64.0,28.0,246.0,19.8,0.513,Medium,NO,2023-10-20,1
664,P00777,67,male,0,136.000000,79.0,63.0,181.0,36.4,0.050,Low,YES,2024-02-25,0
686,P00348,22,male,5,144.000000,82.0,33.0,124.0,27.1,0.125,High,NO,2023-04-03,0
707,P00014,25,female,0,120.000000,65.0,22.0,10.0,29.7,0.552,Medium,NO,2023-04-25,0
801,P00826,79,male,0,124.000000,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0
936,P00409,66,female,0,117.855165,73.0,26.0,232.0,31.9,0.624,Low,YES,2024-12-11,1
937,P00455,73,male,0,115.000000,53.0,24.0,124.0,31.7,0.131,Low,YES,2023-08-26,0
962,P00501,39,male,0,92.000000,62.0,45.0,16.0,34.5,0.143,Medium,YES,2023-10-01,0

remove and record

In [297]:
df=df.drop_duplicates()

check for repeated identifier

In [298]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
963    False
964    False
965    False
966    False
967    False
Length: 950, dtype: bool

save the cleaning dataset

In [301]:
df.to_csv(r'C:\Users\fathi\OneDrive\Desktop\5thsem_OJT\project_diabetes\data\processed\project_databetes_cleaned.csv',index=False)