In [76]:
import pandas as pd
import numpy as np

In [77]:
df=pd.read_csv(r'C:\Users\fathi\OneDrive\Desktop\5thsem_OJT\project_diabetes\data\processed\risvana_p1w2_features.csv',parse_dates=["last_checkup_date"])

In [78]:
df.shape

(950, 21)

In [79]:
df['outcome'].value_counts(normalize=True)

outcome
0    0.712632
1    0.287368
Name: proportion, dtype: float64

# classification and the split

In [80]:
df.columns

Index(['patient_id', 'age', 'gender', 'pregnancies', 'glucose',
       'blood_pressure', 'skin_thickness', 'insulin', 'bmi',
       'diabetes_pedigree', 'physical_activity', 'smoker', 'last_checkup_date',
       'outcome', 'age band', 'bmi category', 'glucose category',
       'insulin_glucose_ratio', 'pregnancies_age_rate', 'days_since_checkup',
       'smoker_activity'],
      dtype='str')

separate the feature from the target

In [81]:
feature_cols = [
    'age',
    'pregnancies',
    'glucose',
    'blood_pressure',
    'skin_thickness',
    'insulin',
    'bmi',
    'diabetes_pedigree',
    'bmi category',
    'glucose category'
]

In [82]:
X = df[feature_cols]
Y = df["outcome"]

In [83]:
X

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi category,glucose category
0,79,0,124.000000,71.0,30.0,124.0,23.4,0.588,normal,prediabetic
1,37,0,153.000000,85.0,24.0,42.0,33.9,0.192,obese,diabetic
2,39,0,142.000000,68.0,22.0,159.0,26.9,0.777,over weight,diabetic
3,68,7,121.000000,88.0,26.0,124.0,29.0,1.217,over weight,prediabetic
4,75,0,107.000000,84.0,31.0,101.0,21.2,0.278,normal,prediabetic
...,...,...,...,...,...,...,...,...,...,...
945,64,2,117.855165,81.0,34.0,124.0,40.3,0.641,obese,prediabetic
946,71,0,140.000000,64.0,37.0,124.0,33.4,0.116,obese,diabetic
947,40,0,130.000000,73.0,26.0,258.0,20.1,0.709,normal,diabetic
948,52,4,123.000000,76.0,22.0,189.0,38.9,0.540,obese,prediabetic
949,42,0,114.000000,73.0,34.0,124.0,28.2,0.819,over weight,prediabetic

In [84]:
Y

0      0
1      1
2      0
3      1
4      0
      ..
945    0
946    1
947    0
948    0
949    0
Name: outcome, Length: 950, dtype: int64

In [85]:
X = pd.get_dummies(X,drop_first=True)

In [86]:
X.shape

(950, 13)

split into tttraining and test sets

In [87]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\fathi\miniconda3\envs\my_env\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\fathi\miniconda3\envs\my_env\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\fathi\miniconda3\envs\my_env\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\fathi\miniconda3\envs\my_env\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\fathi\miniconda3\envs\my_env\Lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\fathi\miniconda3\envs\my_env\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\fathi\miniconda3\envs\my_env\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [88]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(
    X,Y, test_size=0.2, random_state=42, stratify=Y
)
#same random result repeat cheyyan.

In [89]:
X_test.shape

(190, 13)

In [90]:
X_train.shape

(760, 13)

confirm the split behaved

In [91]:
print(Y_train.value_counts(normalize=True))
print(Y_test.value_counts(normalize=True))

outcome
0    0.713158
1    0.286842
Name: proportion, dtype: float64
outcome
0    0.710526
1    0.289474
Name: proportion, dtype: float64

# building the baseline

In [92]:
X

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi category_obese,bmi category_over weight,bmi category_underweights,glucose category_normal,glucose category_prediabetic
0,79,0,124.000000,71.0,30.0,124.0,23.4,0.588,False,False,False,False,True
1,37,0,153.000000,85.0,24.0,42.0,33.9,0.192,True,False,False,False,False
2,39,0,142.000000,68.0,22.0,159.0,26.9,0.777,False,True,False,False,False
3,68,7,121.000000,88.0,26.0,124.0,29.0,1.217,False,True,False,False,True
4,75,0,107.000000,84.0,31.0,101.0,21.2,0.278,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,64,2,117.855165,81.0,34.0,124.0,40.3,0.641,True,False,False,False,True
946,71,0,140.000000,64.0,37.0,124.0,33.4,0.116,True,False,False,False,False
947,40,0,130.000000,73.0,26.0,258.0,20.1,0.709,False,False,False,False,False
948,52,4,123.000000,76.0,22.0,189.0,38.9,0.540,True,False,False,False,True
949,42,0,114.000000,73.0,34.0,124.0,28.2,0.819,False,True,False,False,True

IMPORT YOUR MODEL AND SCALER

In [93]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scale your features

In [94]:
scaler = StandardScaler()
#fit_transform(X_train) → training data-yil ninn scaling learn cheythu apply cheyyunnu
#transform(X_test) → same scaling test data-il apply cheyyunnu
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [95]:
X_train

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi category_obese,bmi category_over weight,bmi category_underweights,glucose category_normal,glucose category_prediabetic
674,62,0,119.000000,70.0,21.0,101.0,25.1,0.672,False,True,False,False,True
56,24,5,109.000000,72.0,27.0,10.0,51.5,0.585,True,False,False,False,True
272,25,2,90.000000,69.0,26.0,967.0,37.0,0.515,True,False,False,True,False
816,67,8,84.000000,61.0,34.0,906.0,41.4,0.087,True,False,False,True,False
558,76,0,132.000000,65.0,26.0,124.0,31.1,0.541,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,39,0,127.000000,66.0,27.0,124.0,42.0,0.562,True,False,False,False,False
307,64,0,99.000000,61.0,12.0,124.0,34.4,0.291,True,False,False,True,False
591,43,3,127.000000,79.0,5.0,81.0,38.8,0.640,True,False,False,False,False
741,23,2,117.855165,66.0,17.0,173.0,32.8,0.503,True,False,False,False,True
919,75,0,148.000000,72.0,22.0,77.0,23.7,0.592,False,False,False,False,False

fit the baseline model

In [96]:
#max_iter = 1000 → maximum 1000 attempts/iterations vare model train cheyyum.
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled,Y_train)

LogisticRegression(max_iter=1000)

predict on the test

In [97]:
Y_pred = model.predict(X_test_scaled)
Y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

eyeball the first ten prediction

In [98]:
pd.DataFrame({"acutal":Y_test.values[:10],
            "predicted":Y_pred[:10]})

   acutal  predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       1          0
5       0          0
6       0          0
7       1          0
8       0          0
9       0          0

compute test accuracy

In [99]:
from sklearn.metrics import accuracy_score
test_acc=accuracy_score(Y_test,Y_pred)
print("test accuray =",test_acc)
#correct

test accuray = 0.7526315789473684

checking for overfitting

In [100]:
train_acc=accuracy_score(Y_train,model.predict(X_train_scaled))
print(train_acc,test_acc)
print(train_acc-test_acc)

0.7394736842105263 0.7526315789473684
-0.013157894736842146

read the models coefficients

In [101]:
coefs = pd.Series(model.coef_[0], index=X.columns)
coefs

age                             0.491292
pregnancies                     0.038351
glucose                         0.733848
blood_pressure                 -0.079047
skin_thickness                  0.008147
insulin                         0.145458
bmi                             0.013643
diabetes_pedigree               0.315200
bmi category_obese              0.229525
bmi category_over weight       -0.012534
bmi category_underweights      -0.068681
glucose category_normal        -0.185230
glucose category_prediabetic    0.026716
dtype: float64

In [102]:
coefs.sort_index()

age                             0.491292
blood_pressure                 -0.079047
bmi                             0.013643
bmi category_obese              0.229525
bmi category_over weight       -0.012534
bmi category_underweights      -0.068681
diabetes_pedigree               0.315200
glucose                         0.733848
glucose category_normal        -0.185230
glucose category_prediabetic    0.026716
insulin                         0.145458
pregnancies                     0.038351
skin_thickness                  0.008147
dtype: float64

In [103]:
coefs.abs().sort_values(ascending=False)

glucose                         0.733848
age                             0.491292
diabetes_pedigree               0.315200
bmi category_obese              0.229525
glucose category_normal         0.185230
insulin                         0.145458
blood_pressure                  0.079047
bmi category_underweights       0.068681
pregnancies                     0.038351
glucose category_prediabetic    0.026716
bmi                             0.013643
bmi category_over weight        0.012534
skin_thickness                  0.008147
dtype: float64

In [104]:
ranked = coefs.reindex(coefs.abs().sort_values(ascending=False).index)
ranked.round(4)
#Ranked = order / position anusarichu arrange cheythathu.

glucose                         0.7338
age                             0.4913
diabetes_pedigree               0.3152
bmi category_obese              0.2295
glucose category_normal        -0.1852
insulin                         0.1455
blood_pressure                 -0.0790
bmi category_underweights      -0.0687
pregnancies                     0.0384
glucose category_prediabetic    0.0267
bmi                             0.0136
bmi category_over weight       -0.0125
skin_thickness                  0.0081
dtype: float64

look at the probabilities behind  the predictions

In [105]:
probs = model.predict_proba(X_test_scaled)[:,1]
probs[:10].round(3)

array([0.289, 0.032, 0.182, 0.182, 0.177, 0.161, 0.419, 0.473, 0.286,
       0.121])

# EVALUATION MATRIX

bulding the confusion matrix

In [106]:
from sklearn.metrics import confusion_matrix 
cm=confusion_matrix(Y_test, Y_pred)
print(cm)
tn, fp, fn, tp = cm.ravel()
print("False positives:", fp)

print("False negatives:", fn)

print("True positives :", tp)
print("True negatives :", tn)

[[127   8]
 [ 39  16]]
False positives: 8
False negatives: 39
True positives : 16
True negatives : 127

# all foure cells, in pattent terms

| Cell   |   Count | What it means for real patients                          |
| ------ | ------: | -------------------------------------------------------- |
| **TN** | **127** | Predicted **no diabetes** and actually **no diabetes**   |
| **FP** |   **8** | Predicted **diabetes**, but actually **no diabetes**     |
| **FN** |  **39** | Predicted **no diabetes**, but actually **had diabetes** |
| **TP** |  **16** | Predicted **diabetes** and actually **had diabetes**     |

In [107]:
missed_rate = fn / (fn + tp)

print("Diabetic patients in the test set :", fn+tp) 
print("Found by the model                :", tp)
print("Missed by the model               :",fn)
print("Proportion missed                 :",round(missed_rate,4))

Diabetic patients in the test set : 55
Found by the model                : 16
Missed by the model               : 39
Proportion missed                 : 0.7091

writte a reusable  evaluation function

In [108]:
def evaluate_model(name, model, X_test, y_test):
    Y_pred = model.predict(X_test)
    acc =accuracy_score(y_test, Y_pred)
    cm = confusion_matrix(y_test, Y_pred)
    tn, fp, fn, tp = cm.ravel()

    print(name)
    print ("accuracy:", round(acc, 4))
    print("confusion_matrix:", cm.tolist())
    print("dibetics found :", tp, "of" , tp+fp)
    print ("missed:", fn)

    return{"model":name,"accuracy":round(acc,4),"found":tp,"missed":fn}

In [109]:
baseline_result = evaluate_model(
    "logistic regression (baseline)", model, X_test_scaled, Y_test)

logistic regression (baseline)
accuracy: 0.7526
confusion_matrix: [[127, 8], [39, 16]]
dibetics found : 16 of 24
missed: 39

In [120]:
stability=[]
for seed in [0,7,42,99,2026]:
    xtr, xte, ytr, yte = train_test_split(
        X,Y,test_size=0.2, random_state=seed, stratify=Y)
    sc = StandardScaler().fit(xtr)
    m = LogisticRegression(max_iter=1000).fit(sc.transform(xtr),ytr)
    pred = m.predict(sc.transform(xte))
    cmx= confusion_matrix(yte,pred)
    stability.append({
        "random_state":seed,
        "accuracy":round(accuracy_score(yte,pred),4),
        "missed":int(cmx[1,0]),
    })
stab = pd.DataFrame(stability)
print(stab.to_string(index=False))

 random_state  accuracy  missed
            0    0.7053      43
            7    0.7000      41
           42    0.7526      39
           99    0.6789      40
         2026    0.6789      41

In [ ]:
raise