In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\fathi\OneDrive\Desktop\5thsem_OJT\project_diabetes\data\raw\project1_diabetes_raw.csv')

confrm the load succeeded

In [4]:
len(df)

968

load only the first few rows

In [5]:
df_100=pd.read_csv(r'C:\Users\fathi\OneDrive\Desktop\5thsem_OJT\project_diabetes\data\raw\project1_diabetes_raw.csv')

In [6]:
len(df_100)

968

record the dataset dimensions

In [7]:
df.shape

(968, 14)

In [8]:
df.shape[0]

968

In [9]:
df.shape[1]

14

list every column name

In [10]:
df.columns.to_list()

['patient_id',
 'age',
 'gender',
 'pregnancies',
 'glucose',
 'blood_pressure',
 'skin_thickness',
 'insulin',
 'bmi',
 'diabetes_pedigree',
 'physical_activity',
 'smoker',
 'last_checkup_date',
 'outcome']

inpest the inferrend types

In [11]:
df.dtypes

patient_id               str
age                  float64
gender                   str
pregnancies            int64
glucose                int64
blood_pressure         int64
skin_thickness         int64
insulin                int64
bmi                  float64
diabetes_pedigree    float64
physical_activity        str
smoker                   str
last_checkup_date        str
outcome                int64
dtype: object

In [12]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79.0,male,0,124,71,30,0,23.4,0.588,NaN,No,20/04/2023,0
1,P00108,37.0,Male,0,153,85,24,42,33.9,0.192,medium,Y,03/05/2024,1
2,P00517,39.0,F,0,142,68,22,159,26.9,0.777,low,NaN,08/07/2023,0
3,P00687,68.0,female,7,121,88,0,0,29.0,1.217,NaN,Y,14/04/2024,1
4,P00927,75.0,female,0,107,84,31,101,21.2,0.278,Low,No,27/01/2024,0
5,P00755,37.0,female,0,145,80,0,0,22.0,0.488,HIGH,Yes,10/01/2024,0
6,P00431,58.0,Male,5,95,72,0,170,27.2,0.197,HIGH,N,25/12/2023,0
7,P00542,58.0,Female,3,150,68,17,0,46.0,0.808,Medium,No,20/06/2024,1
8,P00929,32.0,Female,6,129,74,0,226,20.6,0.655,High,NaN,15/10/2023,1
9,P00513,61.0,Female,0,161,77,35,201,35.0,1.229,Medium,Y,22/12/2023,1

look at the bottom of the file

In [13]:
df.tail(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
958,P00584,47.0,Female,0,107,59,26,98,32.7,0.050,HIGH,No,20/07/2023,0
959,P00674,42.0,Female,5,124,71,22,121,NaN,0.400,NaN,N,01/06/2024,0
960,P00333,59.0,Male,0,141,67,44,305,28.8,0.705,Low,NaN,27/03/2023,1
961,P00270,36.0,Male,0,99,52,13,10,20.8,0.432,medium,Y,12/05/2024,0
962,P00501,39.0,Male,0,92,62,45,16,34.5,0.143,Medium,Yes,01/10/2023,0
963,P00338,64.0,male,2,0,81,34,0,40.3,0.641,Medium,Yes,17/11/2023,0
964,P00092,71.0,F,0,140,64,37,0,33.4,0.116,Low,Y,20/05/2023,1
965,P00081,40.0,Female,0,130,73,0,258,20.1,0.709,Low,N,07/06/2023,0
966,P00704,52.0,F,4,123,76,22,189,38.9,0.540,High,N,05/06/2024,0
967,P00922,42.0,Male,0,114,73,34,0,28.2,0.819,medium,N,10/10/2023,0

take a reproducible random sample

In [14]:
df.sample(10,random_state=7)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
684,P00739,23.0,female,0,131,66,0,68,23.4,0.653,low,No,03/07/2024,0
564,P00518,74.0,Female,0,104,76,21,0,39.8,0.926,low,Yes,14/07/2024,0
384,P00688,26.0,Male,0,124,74,22,197,30.7,0.612,medium,N,08/06/2023,0
24,P00836,66.0,M,5,115,70,21,42,18.9,0.403,Medium,N,28/07/2023,0
299,P00121,51.0,Female,6,122,77,32,188,35.9,0.184,NaN,N,15/01/2023,0
171,P00203,53.0,Male,0,82,80,42,146,34.1,0.881,Medium,Yes,15/12/2023,0
839,P00844,79.0,F,2,107,62,16,62,34.8,0.050,HIGH,NaN,23/07/2023,0
568,P00009,76.0,Female,0,132,65,0,0,NaN,0.541,High,N,11/01/2024,0
351,P00823,39.0,Female,7,94,90,0,0,NaN,0.541,low,N,14/07/2023,0
168,P00180,38.0,Female,0,75,56,0,86,29.8,0.473,low,N,22/07/2024,0

run the schema view

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 968 entries, 0 to 967
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         968 non-null    str
 1   age                959 non-null    float64
 2   gender             968 non-null    str
 3   pregnancies        968 non-null    int64
 4   glucose            968 non-null    int64
 5   blood_pressure     968 non-null    int64
 6   skin_thickness     968 non-null    int64
 7   insulin            968 non-null    int64
 8   bmi                930 non-null    float64
 9   diabetes_pedigree  968 non-null    float64
 10  physical_activity  910 non-null    str
 11  smoker             921 non-null    str
 12  last_checkup_date  968 non-null    str
 13  outcome            968 non-null    int64
dtypes: float64(3), int64(6), str(5)
memory usage: 106.0 KB

In [16]:
df.describe(include="all")

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
count,968,959.000000,968,968.000000,968.000000,968.000000,968.000000,968.000000,930.000000,968.000000,910,921,968,968.000000
unique,950,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,4,499,NaN
top,P00826,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medium,N,11/01/2024,NaN
freq,2,NaN,223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159,380,8,NaN
mean,NaN,49.883212,NaN,1.841942,114.324380,68.558884,20.596074,97.250000,30.796452,0.461834,NaN,NaN,NaN,0.286157
std,NaN,17.581570,NaN,2.616236,34.571781,19.449206,14.174823,118.072391,9.346399,0.285026,NaN,NaN,NaN,0.452197
min,NaN,21.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,NaN,NaN,NaN,0.000000
25%,NaN,35.000000,NaN,0.000000,95.000000,63.000000,8.000000,0.000000,26.200000,0.243500,NaN,NaN,NaN,0.000000
50%,NaN,50.000000,NaN,0.000000,116.000000,71.000000,22.000000,83.000000,30.900000,0.445500,NaN,NaN,NaN,0.000000
75%,NaN,65.000000,NaN,4.000000,136.000000,79.000000,31.000000,161.000000,35.675000,0.654250,NaN,NaN,NaN,1.000000
max,NaN,81.000000,NaN,8.000000,215.000000,107.000000,67.000000,1399.000000,94.500000,1.532000,NaN,NaN,NaN,1.000000

count distinct values in every text column

In [ ]:
df['gender']